name: Check

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - uses: actions/checkout@v4
      - name: Run trunk
        uses: trunk-io/trunk-action@v1
      - name: Run tests
        run: go test -coverprofile coverage.out ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
