name: Check

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - example/**
      - "**/*.md"
      - "**/*.yaml"
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: 🧹 Lint
        uses: golangci/golangci-lint-action@v4
      - name: Install dependencies
        run: go install gotest.tools/gotestsum@latest
      - name: 🧪 Test
        run: gotestsum --junitfile junit.xml --format testdox -- -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
